// Optional UI check: PLAYWRIGHT_MODULE=/absolute/path/to/playwright node tests/desktop-smoke.cjs
const { _electron: electron } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const data = fs.mkdtempSync(path.join(os.tmpdir(), 'bujo-desktop-'));
const output = path.join(root, '.runtime/qa');
fs.mkdirSync(output, { recursive: true });
let app;
const errors = [];
async function launch() {
  app = await electron.launch({
    executablePath: path.join(root, 'node_modules/electron/dist', process.platform === 'win32' ? 'electron.exe' : 'electron'),
    args: [root], env: { ...process.env, BUJO_DATA_DIR: data }, timeout: 30000,
  });
  const page = await app.firstWindow();
  page.on('pageerror', e => errors.push(e.message));
  await page.waitForLoadState('domcontentloaded');
  return page;
}
async function main() {
  let page = await launch();
  await page.getByRole('heading', { name: /Your journal/ }).waitFor();
  await page.screenshot({ path: path.join(output, 'welcome.png') });
  await page.getByRole('textbox', { name: 'Full name' }).fill('QA Alex');
  await page.getByRole('button', { name: 'Create my space' }).click();
  await page.getByRole('button', { name: 'Add your first journal' }).click();
  await page.getByLabel('Starting index').selectOption('main');
  await page.getByRole('button', { name: 'Add journal', exact: true }).click();
  await page.getByRole('heading', { name: 'Bullet Journal 2026/2027/2028', exact: true }).waitFor();
  assert.equal(await page.getByRole('row').count(), 53);
  await page.getByRole('button', { name: 'Add spread', exact: false }).click();
  await page.getByLabel('Spread title').fill('Quiet plans');
  await page.getByLabel('First page').fill('2');
  await page.getByLabel('Last page').fill('3');
  await page.getByRole('button', { name: 'Add spread', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: /already belong/ }).waitFor();
  await page.getByLabel('First page').fill('10');
  await page.getByLabel('Last page').fill('11');
  await page.getByRole('button', { name: 'Add spread', exact: true }).click();
  await page.getByRole('cell', { name: 'Quiet plans', exact: true }).waitFor();
  await page.getByRole('searchbox').fill('Quiet plans');
  assert.equal(await page.getByRole('row').count(), 2);
  await page.getByRole('searchbox').fill('');
  await page.getByRole('button', { name: 'Edit Quiet plans', exact: true }).click();
  await page.getByLabel('Spread title').fill('Quiet plans revised');
  await page.getByRole('button', { name: 'Save spread', exact: true }).click();
  await page.getByRole('cell', { name: 'Quiet plans revised', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Edit journal', exact: true }).click();
  await page.getByLabel('Journal title').fill('My 2026–2028 journal');
  await page.getByLabel('Page count').fill('199');
  await page.getByRole('button', { name: 'Save journal', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: /exclude/ }).waitFor();
  await page.getByLabel('Page count').fill('200');
  await page.getByRole('button', { name: 'Save journal', exact: true }).click();
  await page.getByRole('heading', { name: 'My 2026–2028 journal' }).waitFor();
  await page.screenshot({ path: path.join(output, 'journal.png') });
  await page.setViewportSize({ width: 760, height: 580 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await app.close(); app = null;
  page = await launch();
  await page.getByRole('heading', { name: 'My 2026–2028 journal', exact: true }).waitFor();
  await page.getByRole('cell', { name: 'Quiet plans revised', exact: true }).waitFor();
  await page.getByRole('button', { name: /Switch or add profile/ }).click();
  await page.getByRole('button', { name: /Create a profile/ }).click();
  await page.getByRole('textbox', { name: 'Full name' }).fill('QA Sam');
  await page.getByRole('button', { name: 'Create profile', exact: true }).click();
  await page.getByRole('button', { name: 'Add your first journal' }).waitFor();
  assert.equal(await page.getByRole('button', { name: /Bullet Journal 2026/ }).count(), 0);
  await page.getByRole('button', { name: 'Add your first journal' }).click();
  await page.getByLabel('Journal title').fill('New notebook 2029');
  await page.getByLabel('Page count').fill('96');
  await page.getByLabel('Notebook size').selectOption('Custom');
  await page.getByLabel('Custom size').fill('15 × 21 cm');
  await page.getByRole('button', { name: 'Add journal', exact: true }).click();
  await page.getByRole('heading', { name: 'New notebook 2029' }).waitFor();
  await app.close(); app = null;
  page = await launch();
  await page.getByRole('heading', { name: 'Whose journal shelf?' }).waitFor();
  await page.getByRole('button', { name: /^QA Alex/ }).click();
  await page.getByRole('cell', { name: 'Quiet plans revised', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: /New notebook 2029/ }).count(), 0);
  const backupPath = path.join(data, 'test-backup.json');
  await app.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }); }, backupPath);
  await page.getByRole('button', { name: 'Backups', exact: true }).click();
  await page.getByRole('button', { name: 'Export all profiles', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Backup exported.' }).waitFor();
  assert.equal(JSON.parse(fs.readFileSync(backupPath, 'utf8')).state.profiles.length, 2);
  await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, backupPath);
  await page.getByRole('button', { name: 'Choose backup to import' }).click();
  await page.getByRole('heading', { name: 'Profiles to add' }).waitFor();
  assert.equal(JSON.parse(fs.readFileSync(path.join(data, 'journals.json'), 'utf8')).profiles.length, 2);
  await page.getByRole('button', { name: 'Import as new profiles' }).click();
  await page.getByRole('button', { name: /^QA Alex \(import 1\)/ }).waitFor();
  assert.equal(JSON.parse(fs.readFileSync(path.join(data, 'journals.json'), 'utf8')).profiles.length, 4);
  await page.getByRole('button', { name: 'Backups', exact: true }).click();
  await app.evaluate(({ dialog }) => { dialog.showOpenDialog = async () => ({ canceled: true, filePaths: [] }); });
  await page.getByRole('button', { name: 'Choose backup to import' }).click();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  assert.equal(JSON.parse(fs.readFileSync(path.join(data, 'journals.json'), 'utf8')).profiles.length, 4);
  await page.getByRole('button', { name: 'Delete profile QA Sam (import 1)', exact: true }).click();
  await page.getByLabel('Type the profile name to confirm').fill('Wrong name');
  await page.getByRole('button', { name: 'Delete profile', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: /exactly/ }).waitFor();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  assert.equal(JSON.parse(fs.readFileSync(path.join(data, 'journals.json'), 'utf8')).profiles.length, 4);
  await page.getByRole('button', { name: 'Delete profile QA Sam (import 1)', exact: true }).click();
  await page.getByLabel('Type the profile name to confirm').fill('QA Sam (import 1)');
  await page.getByRole('button', { name: 'Delete profile', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Profile deleted' }).waitFor();
  const remaining = JSON.parse(fs.readFileSync(path.join(data, 'journals.json'), 'utf8')).profiles;
  assert.equal(remaining.length, 3);
  assert.ok(remaining.some(p => p.name === 'QA Sam'));
  assert.ok(!remaining.some(p => p.name === 'QA Sam (import 1)'));
  assert.deepEqual(errors, []);
  console.log('PASS: onboarding, templates, editing, invalid page shrink, spread validation, search, narrow layout, restart persistence, profile isolation, export, preview/import copies canceled import, exact-name profile deletion and cancellation. No renderer errors.');
}
main().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => {
  if (app) await app.close();
  fs.rmSync(data, { recursive: true, force: true });
});
